(function(){function n(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var r=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,e){if(a==Array.prototype||a==Object.prototype)return a;a[b]=e.value;return a}; 
function t(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var e=a[b];if(e&&e.Math==Math)return e}throw Error("Cannot find global object");}var u=t(this);function v(a,b){if(b)a:{var e=u;a=a.split(".");for(var d=0;d<a.length-1;d++){var h=a[d];if(!(h in e))break a;e=e[h]}a=a[a.length-1];d=e[a];b=b(d);b!=d&&b!=null&&r(e,a,{configurable:!0,writable:!0,value:b})}} 
v("Symbol",function(a){function b(l){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new e(d+(l||"")+"_"+h++,l)}function e(l,c){this.g=l;r(this,"description",{configurable:!0,writable:!0,value:c})}if(a)return a;e.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",h=0;return b}); 
v("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),e=0;e<b.length;e++){var d=u[b[e]];typeof d==="function"&&typeof d.prototype[a]!="function"&&r(d.prototype,a,{configurable:!0,writable:!0,value:function(){return w(n(this))}})}return a});function w(a){a={next:a};a[Symbol.iterator]=function(){return this};return a} 
function x(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:n(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function y(a){return z(a,a)}function z(a,b){a.raw=b;Object.freeze&&(Object.freeze(a),Object.freeze(b));return a} 
var A=typeof Object.assign=="function"?Object.assign:function(a,b){for(var e=1;e<arguments.length;e++){var d=arguments[e];if(d)for(var h in d)Object.prototype.hasOwnProperty.call(d,h)&&(a[h]=d[h])}return a};v("Object.assign",function(a){return a||A});function B(){this.l=!1;this.h=null;this.o=void 0;this.g=1;this.B=this.j=0;this.i=null}function C(a){if(a.l)throw new TypeError("Generator is already running");a.l=!0}B.prototype.A=function(a){this.o=a};function G(a,b){a.i={I:b,S:!0};a.g=a.j||a.B} 
B.prototype.return=function(a){this.i={return:a};this.g=this.B};function H(a,b,e){a.g=e;return{value:b}}function I(a){a.j=0;var b=a.i.I;a.i=null;return b}function J(a){this.g=new B;this.h=a}function K(a,b){C(a.g);var e=a.g.h;if(e)return L(a,"return"in e?e["return"]:function(d){return{value:d,done:!0}},b,a.g.return);a.g.return(b);return M(a)} 
function L(a,b,e,d){try{var h=b.call(a.g.h,e);if(!(h instanceof Object))throw new TypeError("Iterator result "+h+" is not an object");if(!h.done)return a.g.l=!1,h;var l=h.value}catch(c){return a.g.h=null,G(a.g,c),M(a)}a.g.h=null;d.call(a.g,l);return M(a)}function M(a){for(;a.g.g;)try{var b=a.h(a.g);if(b)return a.g.l=!1,{value:b.value,done:!1}}catch(e){a.g.o=void 0,G(a.g,e)}a.g.l=!1;if(a.g.i){b=a.g.i;a.g.i=null;if(b.S)throw b.I;return{value:b.return,done:!0}}return{value:void 0,done:!0}} 
function N(a){this.next=function(b){C(a.g);a.g.h?b=L(a,a.g.h.next,b,a.g.A):(a.g.A(b),b=M(a));return b};this.throw=function(b){C(a.g);a.g.h?b=L(a,a.g.h["throw"],b,a.g.A):(G(a.g,b),b=M(a));return b};this.return=function(b){return K(a,b)};this[Symbol.iterator]=function(){return this}}function O(a){function b(d){return a.next(d)}function e(d){return a.throw(d)}return new Promise(function(d,h){function l(c){c.done?d(c.value):Promise.resolve(c.value).then(b,e).then(l,h)}l(a.next())})} 
function P(a){return O(new N(new J(a)))}function Q(){for(var a=Number(this),b=[],e=a;e<arguments.length;e++)b[e-a]=arguments[e];return b}v("globalThis",function(a){return a||u}); 
v("Promise",function(a){function b(c){this.h=0;this.i=void 0;this.g=[];this.A=!1;var f=this.j();try{c(f.resolve,f.reject)}catch(g){f.reject(g)}}function e(){this.g=null}function d(c){return c instanceof b?c:new b(function(f){f(c)})}if(a)return a;e.prototype.h=function(c){if(this.g==null){this.g=[];var f=this;this.i(function(){f.l()})}this.g.push(c)};var h=u.setTimeout;e.prototype.i=function(c){h(c,0)};e.prototype.l=function(){for(;this.g&&this.g.length;){var c=this.g;this.g=[];for(var f=0;f<c.length;++f){var g= 
c[f];c[f]=null;try{g()}catch(k){this.j(k)}}}this.g=null};e.prototype.j=function(c){this.i(function(){throw c;})};b.prototype.j=function(){function c(k){return function(m){g||(g=!0,k.call(f,m))}}var f=this,g=!1;return{resolve:c(this.L),reject:c(this.l)}};b.prototype.L=function(c){if(c===this)this.l(new TypeError("A Promise cannot resolve to itself"));else if(c instanceof b)this.N(c);else{a:switch(typeof c){case "object":var f=c!=null;break a;case "function":f=!0;break a;default:f=!1}f?this.K(c):this.o(c)}}; 
b.prototype.K=function(c){var f=void 0;try{f=c.then}catch(g){this.l(g);return}typeof f=="function"?this.O(f,c):this.o(c)};b.prototype.l=function(c){this.B(2,c)};b.prototype.o=function(c){this.B(1,c)};b.prototype.B=function(c,f){if(this.h!=0)throw Error("Cannot settle("+c+", "+f+"): Promise already settled in state"+this.h);this.h=c;this.i=f;this.h===2&&this.M();this.U()};b.prototype.M=function(){var c=this;h(function(){if(c.J()){var f=u.console;typeof f!=="undefined"&&f.error(c.i)}},1)};b.prototype.J= 
function(){if(this.A)return!1;var c=u.CustomEvent,f=u.Event,g=u.dispatchEvent;if(typeof g==="undefined")return!0;typeof c==="function"?c=new c("unhandledrejection",{cancelable:!0}):typeof f==="function"?c=new f("unhandledrejection",{cancelable:!0}):(c=u.document.createEvent("CustomEvent"),c.initCustomEvent("unhandledrejection",!1,!0,c));c.promise=this;c.reason=this.i;return g(c)};b.prototype.U=function(){if(this.g!=null){for(var c=0;c<this.g.length;++c)l.h(this.g[c]);this.g=null}};var l=new e;b.prototype.N= 
function(c){var f=this.j();c.C(f.resolve,f.reject)};b.prototype.O=function(c,f){var g=this.j();try{c.call(f,g.resolve,g.reject)}catch(k){g.reject(k)}};b.prototype.then=function(c,f){function g(p,q){return typeof p=="function"?function(D){try{k(p(D))}catch(E){m(E)}}:q}var k,m,F=new b(function(p,q){k=p;m=q});this.C(g(c,k),g(f,m));return F};b.prototype.catch=function(c){return this.then(void 0,c)};b.prototype.C=function(c,f){function g(){switch(k.h){case 1:c(k.i);break;case 2:f(k.i);break;default:throw Error("Unexpected state: "+ 
k.h);}}var k=this;this.g==null?l.h(g):this.g.push(g);this.A=!0};b.resolve=d;b.reject=function(c){return new b(function(f,g){g(c)})};b.race=function(c){return new b(function(f,g){for(var k=x(c),m=k.next();!m.done;m=k.next())d(m.value).C(f,g)})};b.all=function(c){var f=x(c),g=f.next();return g.done?d([]):new b(function(k,m){function F(D){return function(E){p[D]=E;q--;q==0&&k(p)}}var p=[],q=0;do p.push(void 0),q++,d(g.value).C(F(p.length-1),m),g=f.next();while(!g.done)})};return b});/* 
 
 Copyright Google LLC 
 SPDX-License-Identifier: Apache-2.0 
*/ 
var R=globalThis.trustedTypes,S;function T(){var a=null;if(!R)return a;try{var b=function(e){return e};a=R.createPolicy("goog#html",{createHTML:b,createScript:b,createScriptURL:b})}catch(e){}return a};function U(a){this.g=a}U.prototype.toString=function(){return this.g+""};function V(a){var b;S===void 0&&(S=T());a=(b=S)?b.createScriptURL(a):a;return new U(a)};function W(a){var b=Q.apply(1,arguments);if(b.length===0)return V(a[0]);for(var e=a[0],d=0;d<b.length;d++)e+=encodeURIComponent(b[d])+a[d+1];return V(e)};var aa=y(["https://tpc.googlesyndication.com/sodar/",".js"]),ba=y(["https://ep2.adtrafficquality.google/sodar/",".js"]),ca=y(["https://www.google.com/recaptcha/api2/aframe"]);W(ca);function da(a,b){if(b instanceof U)b=b.g;else throw Error("");a.src=b;var e;b=a.ownerDocument;b=b===void 0?document:b;var d;b=(d=(e=b).querySelector)==null?void 0:d.call(e,"script[nonce]");(e=b==null?"":b.nonce||b.getAttribute("nonce")||"")&&a.setAttribute("nonce",e)};function ea(a,b){typeof a.addEventListener==="function"&&a.addEventListener.call(a,"load",b,!1)};function fa(a){var b=window,e=!0;e=e===void 0?!1:e;new Promise(function(d,h){function l(){c.onload=null;c.onerror=null;var f;(f=c.parentElement)==null||f.removeChild(c)}var c=b.document.createElement("script");c.onload=function(){l();d()};c.onerror=function(){l();h(void 0)};c.type="text/javascript";da(c,a);e&&b.document.readyState!=="complete"?ea(b,function(){b.document.body.appendChild(c)}):b.document.body.appendChild(c)})};var X={},ha=(X["internal-error"]=-1,X["non-recoverable-error"]=-2,X["api-disabled-by-application"]=-3,X["invalid-argument"]=-4,X["token-provider-invalid"]=-5,X);function ia(){this.m=!1}var Y;function Z(){Y||(Y=new ia);return Y} 
function ja(a){var b;P(function(e){if(e.g==1)return e.j=2,H(e,window.android.webview.getExperimentalMediaIntegrityTokenProvider({cloudProjectNumber:187810013193}),4);if(e.g!=2)a.h=e.o,a.g=void 0,e.g=0,e.j=0;else{b=I(e);var d=0;b.mediaIntegrityErrorName?d||(d=ha[b.mediaIntegrityErrorName]):b.code&&(d=b.code());a.g=d;e.g=0}})};function ka(a){var b,e,d,h,l,c,f,g;return P(function(k){switch(k.g){case 1:return b=a.u?"https://ep1.adtrafficquality.google/getconfig/sodar":"https://pagead2.googlesyndication.com/getconfig/sodar",e=b+"?sv=200&tid="+a.g+("&tv="+a.h+"&st=")+a.v,d=void 0,k.j=2,H(k,la(e),4);case 4:d=k.o;k.g=3;k.j=0;break;case 2:I(k);case 3:if(!d)return k.return(void 0);h=a.G||d.sodar_query_id;l=d.rc_enable!==void 0?d.rc_enable:"n";c=d.bg_snapshot_delay_ms===void 0?"0":d.bg_snapshot_delay_ms;f=d.is_gen_204===void 0? 
"1":d.is_gen_204;return h&&d.bg_hash_basename&&d.bg_binary?(g={context:a.i,R:d.bg_hash_basename,P:d.bg_binary,T:a.g+"_"+a.h,G:h,v:a.v,F:l,H:c,D:f,u:a.u},a.m?k.return(Object.assign({},g,{m:!0})):k.return(g)):k.return(void 0)}})}function la(a){return new Promise(function(b,e){var d=new XMLHttpRequest;d.onreadystatechange=function(){d.readyState===d.DONE&&(d.status>=200&&d.status<300?b(JSON.parse(d.responseText)):e())};d.open("GET",a,!0);d.send()})};function ma(a){this.g=a.g;this.h=a.h;this.i=a.i;this.G=a.G;this.v=a.v;this.F=a.F;this.H=a.H;this.D=a.D;this.u=a.u;this.m=a.m}function na(){this.g="xfad";this.h="r20100101";this.i="cr";this.v="env";this.F="n";this.H="0";this.D="1";this.m=this.u=!1}function oa(){var a=new na;a.v="int";return new ma(a)};(function(){var a=oa(),b;P(function(e){if(e.g==1){if(a.m){Z().m=!0;var d=Z();window.android&&window.android.webview&&window.android.webview.getExperimentalMediaIntegrityTokenProvider&&d.m&&ja(d)}return H(e,ka(a),2)}if(b=e.o){d=b;var h="sodar2";h=h===void 0?"sodar2":h;var l=window,c=l.GoogleGcLKhOms;c&&typeof c.push==="function"||(c=l.GoogleGcLKhOms=[]);var f={};f=(f._ctx_=d.context,f._bgv_=d.R,f._bgp_=d.P,f._li_=d.T,f._jk_=d.G,f._st_=d.v,f._rc_=d.F,f._dl_=d.H,f._g2_=d.D,f._atqg_=d.u===void 0?"0": 
d.u?"1":"0",f);if(d.m){var g={};c.push(Object.assign({},f,(g._wvp_="1",g)))}else c.push(f);if(c=l.GoogleDX5YKUSk)l.GoogleDX5YKUSk=void 0,c[1]();d=d.u?W(ba,h):W(aa,h);fa(d)}return e.return(b)})})();}).call(this);
