name: 🔒 Security Vulnerability
description: Report a security vulnerability (Please use private disclosure for critical issues)
title: "[Security]: "
labels: ["security", "needs-triage", "confidential"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        # ⚠️ IMPORTANT SECURITY NOTICE ⚠️
        
        **For critical security vulnerabilities, please DO NOT use this public issue tracker.**
        
        Instead, please report critical vulnerabilities privately by:
        1. Emailing security@brokeranalysis.com
        2. Using GitHub's private vulnerability reporting feature
        3. Contacting the maintainers directly
        
        **Use this public template only for:**
        - Low-risk security improvements
        - Security-related feature requests
        - General security hardening suggestions
        - Non-exploitable security observations
        
        Thank you for helping keep BrokerAnalysis secure!

  - type: checkboxes
    id: disclosure-agreement
    attributes:
      label: Responsible Disclosure Agreement
      description: Please confirm your understanding of responsible disclosure
      options:
        - label: I understand this is a public issue tracker and will not disclose critical vulnerabilities here
          required: true
        - label: I have considered the severity of this issue and determined it's appropriate for public disclosure
          required: true
        - label: I will not exploit this vulnerability for malicious purposes
          required: true
        - label: I will allow reasonable time for the team to address this issue before public disclosure
          required: true

  - type: dropdown
    id: severity-level
    attributes:
      label: Severity Level
      description: How would you rate the severity of this security issue?
      options:
        - Low (Information disclosure, minor security improvements)
        - Medium (Limited impact, requires user interaction)
        - High (Significant impact, but limited scope)
        - Critical (Immediate threat, wide impact) - SHOULD BE REPORTED PRIVATELY
    validations:
      required: true

  - type: dropdown
    id: vulnerability-type
    attributes:
      label: Vulnerability Type
      description: What type of security issue is this?
      options:
        - Authentication bypass
        - Authorization issues
        - Cross-Site Scripting (XSS)
        - Cross-Site Request Forgery (CSRF)
        - SQL Injection
        - Information disclosure
        - Insecure data storage
        - Insecure communication
        - Input validation issues
        - Session management
        - Cryptographic issues
        - Dependency vulnerabilities
        - Configuration issues
        - Privacy concerns
        - Other
    validations:
      required: true

  - type: textarea
    id: vulnerability-description
    attributes:
      label: Vulnerability Description
      description: Describe the security vulnerability or concern
      placeholder: |
        Provide a clear description of the security issue:
        - What is the vulnerability?
        - What systems/components are affected?
        - What is the potential impact?
        
        Note: Avoid providing detailed exploitation steps in public issues
    validations:
      required: true

  - type: dropdown
    id: affected-components
    attributes:
      label: Affected Components
      description: Which parts of the application are affected?
      multiple: true
      options:
        - Authentication system
        - User registration
        - Password reset
        - Session management
        - User profiles
        - Broker data
        - Search functionality
        - AI chat system
        - File uploads
        - API endpoints
        - Database
        - Third-party integrations
        - Frontend components
        - Backend services
        - Infrastructure
        - Other
    validations:
      required: true

  - type: dropdown
    id: attack-vector
    attributes:
      label: Attack Vector
      description: How could this vulnerability be exploited?
      options:
        - Remote network access
        - Local access required
        - Physical access required
        - Social engineering
        - Malicious file/input
        - Browser-based attack
        - API manipulation
        - Database access
        - Configuration exploitation
        - Third-party service
        - Other
    validations:
      required: true

  - type: dropdown
    id: authentication-required
    attributes:
      label: Authentication Required
      description: Does exploiting this vulnerability require authentication?
      options:
        - No authentication required (anonymous)
        - Basic user authentication required
        - Administrative privileges required
        - Special permissions required
        - Unknown
    validations:
      required: true

  - type: dropdown
    id: user-interaction
    attributes:
      label: User Interaction Required
      description: Does exploiting this vulnerability require user interaction?
      options:
        - No user interaction required
        - Minimal user interaction (clicking a link)
        - Moderate user interaction (form submission)
        - Significant user interaction required
        - Unknown
    validations:
      required: true

  - type: textarea
    id: impact-assessment
    attributes:
      label: Impact Assessment
      description: What is the potential impact of this vulnerability?
      placeholder: |
        Describe the potential consequences:
        - Data that could be accessed or modified
        - Systems that could be compromised
        - Users that could be affected
        - Business impact
        
        Consider:
        - Confidentiality impact
        - Integrity impact
        - Availability impact
    validations:
      required: true

  - type: textarea
    id: affected-users
    attributes:
      label: Affected Users
      description: Which users or user types could be affected?
      placeholder: |
        Examples:
        - All users
        - Authenticated users only
        - Administrative users
        - Users with specific permissions
        - Users of specific features
        - External users/visitors
    validations:
      required: true

  - type: textarea
    id: reproduction-info
    attributes:
      label: General Reproduction Information
      description: General information about reproducing this issue (avoid detailed exploitation steps)
      placeholder: |
        Provide general guidance without detailed exploitation steps:
        - What conditions are needed?
        - What user actions trigger the issue?
        - What environment/configuration is required?
        
        Note: For critical vulnerabilities, detailed steps should be shared privately

  - type: dropdown
    id: browsers-affected
    attributes:
      label: Affected Browsers
      description: Which browsers are affected by this vulnerability?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Opera
        - All browsers
        - Not browser-specific
        - Unknown

  - type: dropdown
    id: platforms-affected
    attributes:
      label: Affected Platforms
      description: Which platforms are affected?
      multiple: true
      options:
        - Web application
        - Mobile web
        - API
        - Backend services
        - Database
        - Infrastructure
        - All platforms
        - Unknown

  - type: textarea
    id: evidence
    attributes:
      label: Evidence
      description: Non-sensitive evidence of the vulnerability
      placeholder: |
        Provide non-sensitive evidence such as:
        - Screenshots of error messages (redact sensitive info)
        - Network request/response headers (redact sensitive data)
        - Log entries (redact sensitive information)
        - Code snippets showing the issue (if appropriate)
        
        Important: Do not include:
        - Actual exploits or payloads
        - Sensitive data or credentials
        - Detailed attack vectors
      render: text

  - type: textarea
    id: mitigation-suggestions
    attributes:
      label: Suggested Mitigations
      description: Do you have suggestions for fixing or mitigating this vulnerability?
      placeholder: |
        Suggestions might include:
        - Input validation improvements
        - Authentication enhancements
        - Configuration changes
        - Code modifications
        - Security headers
        - Rate limiting
        - Access controls

  - type: checkboxes
    id: security-best-practices
    attributes:
      label: Related Security Concerns
      description: Are there related security practices that should be considered?
      options:
        - label: This issue affects data encryption
        - label: This issue affects user privacy
        - label: This issue affects compliance requirements (GDPR, etc.)
        - label: This issue affects audit logging
        - label: This issue affects access controls
        - label: This issue affects data retention policies
        - label: This issue affects third-party integrations
        - label: This issue affects API security

  - type: dropdown
    id: discovery-method
    attributes:
      label: Discovery Method
      description: How was this vulnerability discovered?
      options:
        - Manual testing
        - Automated security scanning
        - Code review
        - Penetration testing
        - Bug bounty program
        - User report
        - Security research
        - Incident investigation
        - Other

  - type: input
    id: cve-reference
    attributes:
      label: CVE Reference
      description: If this relates to a known CVE, please provide the reference
      placeholder: e.g., CVE-2023-12345

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to relevant security advisories, documentation, or research
      placeholder: |
        Provide links to:
        - Security advisories
        - OWASP documentation
        - Security research papers
        - Vendor security bulletins
        - Related vulnerability reports

  - type: checkboxes
    id: researcher-info
    attributes:
      label: Researcher Information
      description: Information about security research and disclosure
      options:
        - label: I am a security researcher
        - label: I would like to be credited for this discovery (if appropriate)
        - label: I am available for follow-up questions
        - label: I can assist with testing fixes
        - label: I have additional related findings to share privately

  - type: textarea
    id: timeline
    attributes:
      label: Disclosure Timeline
      description: What is your expected timeline for this issue?
      placeholder: |
        Please indicate:
        - When you discovered this issue
        - Your expected timeline for public disclosure
        - Any deadlines or constraints
        - Coordination with other researchers

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information about this security issue
      placeholder: |
        Additional information that might be helpful:
        - Related security issues
        - Environmental factors
        - Specific configurations
        - Historical context
        - Industry best practices

  - type: markdown
    attributes:
      value: |
        ---
        
        **Thank you for helping improve the security of BrokerAnalysis!**
        
        After submitting this issue:
        1. Our security team will review and respond within 48 hours
        2. We may contact you for additional information
        3. We will work on a fix and coordinate disclosure timing
        4. We will credit you appropriately (if desired and appropriate)
        
        For urgent security issues, please contact us directly at security@brokeranalysis.com